---
- name: Run the image building group of hosts
  hosts: builder
  become: true
  tasks:
    - name: Ensure virt packages are installed.
      yum: name={{ item }} state=installed
      with_items:
        - virt-viewer
        - qemu-kvm
        - libvirt
        - virt-manager
        - virt-install
        - libguestfs-tools

    - name: Ensure libvirtd is started and enabled to start at boot.
      service: name=libvirtd state=started enabled=yes

    - name: Copy build script in place.
      template: src=build.sh.j2 dest=/usr/local/bin/build-image mode=00755

- name: Run the provisioning group of hosts
  hosts: runner
  become: true
  roles:
    - role: init
    - role: neovim
